### ISSUE TITLE
[SUGGESTION] Gifs

### ISSUE THREAD

**Issue by Kris1432** [henkelmax/camera#10]
Have gifs been considered for uploading?

Is this even possible?

**Comment by henkelmax** [comment]
This mod only supports JPG, because it can be compressed a lot. GIFs are hard to implement, have a lot of storage consumption and don't look good. JPG is one of the few image formats that can be used, because if you upload larger images, the upload would lag the server too much.

**Comment by Kris1432** [comment]
Thanks for the answer!

**Comment by henkelmax** [comment]
No problem! Let me know if you have any other suggestions or ideas.

**Comment by Kris1432** [comment]
Was just having a thought if you could add borders to the item frames at all?

Or have another item frame that could enable this instead of implementing it to the current one?

**Comment by henkelmax** [comment]
I thought of that too. But its not that easy to make it look normal when resizing the image, so I decided to make it borderless and leave it up to the image creator to include a frame on the image (Adding a frame in an image editing software and uploading it).
If you have ideas, concepts or designs for a frame, I am always open for stuff.

**Comment by Kris1432** [comment]
I'll have a think about that one and get back to you!
