### ISSUE TITLE
Suddenly unable to import images / Grayed out button

### ISSUE THREAD

**Issue by RemyDeprez** [henkelmax/camera#101]
### Bug description

Hello,
I have tried to import a .gif file (not the smartest idea i know), since then i am not able to click on the upload button, it's grayed out.
I have checked it stills activated from config files.

### Minecraft version

1.18.2

### Mod version

1.18.2-1.0.6

### Mod loader and version

Forge

### Steps to reproduce

1-Go to camera UI
2-Click on import
3-Import a .gif file
4- Re-Open camera UI
5-Upload button is now grayed out

### Expected behavior

Upload button should'not be grayed out since i have not de activated upload from config file.

### Log files

No particular logs found

### Screenshots

![Capture](https://github.com/user-attachments/assets/602f25e1-70db-4189-849f-70b8f1652ee7)

**Comment by RemyDeprez** [comment]
After restarting my game, it seems to work properly and being only a client issue, i do not know if you want to fix that (do not think), feel free to close this issue if it is not relevant, 
Wkr, 
Rémy.

**Comment by henkelmax** [comment]
1.18.2 is no longer supported, sorry.
