### ISSUE TITLE
Camera filters are incompatible with "The Anomaly" mod (Curseforge)

### ISSUE THREAD

**Issue by CodeBot101** [henkelmax/camera#102]
### Bug description

Simple enough: I individually tested all my mods, and the camera filter broke as soon as I installed The Anomaly:

The filter will FLASH on the screen for a split second, but then disappear and go back to the normal camera view. I do not know why this happens. If I had to guess (but don't let me mislead you), it may be to do with some code The Anomaly runs to put scary horror stuff on the screen; that's just a guess though, and some other mods that do similar jump-scare screen overlay things did not conflict with the camera, so I'm not sure what's different about The Anomaly.

It is possible that fixing this error could inadvertently fix other mod errors, as I did have this error weeks ago with different (equally on-screen overlay jumpscary) mods.

### Minecraft version

1.20.1

### Mod version

1.20.1-1.1.2

### Mod loader and version

Forge 47.3.0

### Steps to reproduce

Simply install Camera Mod plus "The Anomaly" by "clorobored," then give yourself a camera and select a filter, then finally enter the viewport of the camera:

Proceed to witness how the filter flashes on screen then disappears, not working :D (lmao)

### Expected behavior

In all my other testing, the camera filter simply appears (and stays) on screen once selected and in the camera's viewport.

### Log files

https://gist.github.com/CodeBot101/b515fe4a16370c21d6659a281731f393

**Comment by CodeBot101** [comment]
(actually after looking at the log, it seems like The Anomaly is trying to remove things constantly—probably a short-cutty way to ensure effects never stay on the screen for too long or something, lol. I suppose you could maybe find a way to circumvent regular overlay commands by creating a separate, custom overlay for your filters, but that might be a lotta work, lol.

That *would* be ideal ultimately though, because as I alluded to, many other horror mods like to use on-screen stuff, so that renders this camera filter not-working for lots of different ppl's mods)

**Comment by henkelmax** [comment]
> (actually after looking at the log, it seems like The Anomaly is trying to remove things constantly—probably a short-cutty way to ensure effects never stay on the screen for too long or something, lol. I suppose you could maybe find a way to circumvent regular overlay commands by creating a separate, custom overlay for your filters, but that might be a lotta work, lol.

This sounds like an issue with the Anomaly mod. Please report it to their issue tracker.

**Comment by CodeBot101** [comment]
> > (actually after looking at the log, it seems like The Anomaly is trying to remove things constantly—probably a short-cutty way to ensure effects never stay on the screen for too long or something, lol. I suppose you could maybe find a way to circumvent regular overlay commands by creating a separate, custom overlay for your filters, but that might be a lotta work, lol.
> 
> This sounds like an issue with the Anomaly mod. Please report it to their issue tracker.

Well yes except that the above (and my experience with similar mods) suggests any mod that tries to clear the effects on screen are liable to also clear the camera effect.

It's maybe more of a general issue with modders using the same overlay functions for their mods, which inevitably causes conflicts, but a persistent effect like a camera filter demands to stay on screen more than a little jumpscare that usually only stays on screen for a second or so anyway, hence why I say it'd be ideal for this mod to look into the workaround—even though that's annoying to hear on your end I'm sure, lol

The alternative is basically us asking/hoping for a bunch of other horror mod creators to change their mods, lol, which is not only less likely but less impactful than this mod finding a workaround/making a custom overlay as those jumpscares don't need to persistently stay on screen like a camera filter ought to

**Comment by henkelmax** [comment]
There can only be one effect active at a time. Other mods shouldn't clear shaders if they didn't enable it.
