### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by itsvinittyy** [henkelmax/camera#103]
### Bug description

The filters don't work on the Camera. When trying to take a photo with the Camera, the desired filter will flash for half a second and then won't work. This doesn't happen on different versions of Minecraft: Java Edition.

See the screenshot below.

### Minecraft version

1.19.2

### Mod version

camera-forge-1.19.2-1.0.14.jar

### Mod loader and version

Forge 43.4.2

### Steps to reproduce

1. Hold shift while holding the Camera.
2. Right click the Camera.
3. Select your desired filter
4. Press ESC to exit the menu
5. Take a photo with the Camera

### Expected behavior

The Camera filter should have been applied when taking photos with the Camera.
As stated, they don't.

### Log files

https://gist.github.com/itsvinittyy/350554872a44c31ef2cce9d61afe9138

### Screenshots

![image](https://github.com/user-attachments/assets/a4f288c0-975c-436c-926b-654162e9bf98)

**Comment by henkelmax** [comment]
And it works in the latest mod version?

**Comment by itsvinittyy** [comment]
latest mod version doesn't support 1.19.2

**Comment by henkelmax** [comment]
Sorry, I meant if it works for the latest Minecraft version.

**Comment by itsvinittyy** [comment]
It works on latest from what I've seen.

**Comment by henkelmax** [comment]
Ok, I guess update to a newer version then. 1.19.2 isn't really getting updates anymore.
