### ISSUE TITLE
Camera Mod is Installed but no items

### ISSUE THREAD

**Issue by AlphaThink13** [henkelmax/camera#104]
### Bug description

Camera mod is installed on my modpack, everything loads just fine, but when I go into the creative inventory I cannot find any of the mod's items

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.14

### Mod loader and version

Forge 47.3.10

### Steps to reproduce

1. Install the mod
2. Load minecraft
3. Look for the items

### Log files

https://gist.github.com/AlphaThink13/345b391e81a576bf6e51c353e3dec41c

### Screenshots

https://kappa.lol/kiKlQ

**Comment by henkelmax** [comment]
Are the items craftable?

**Comment by AlphaThink13** [comment]
I don't know the recipes from memory, haven't used it in survival before. I do have JEI installed, I can check that aswell.

**Comment by AlphaThink13** [comment]
Yes, I can craft the items, but they don't appear on the creative inventory or JEI

**Comment by henkelmax** [comment]
That has been fixed in later versions. So the items exist.
