### ISSUE TITLE
upload button not working

### ISSUE THREAD

**Issue by littilesix** [henkelmax/camera#106]
### Bug description

as the tittle

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.19

### Mod loader and version

forge47..3.12

### Steps to reproduce

click  the button ,the explorer do not shown.
[00:37:24] [Render thread/ERROR]: Received invalid gui properties for screen: class de.maxhenkel.camera.gui.CameraScreen
guiXSize must be greater than 1 and less than 1000000000: 0
guiYSize must be greater than 1 and less than 1000000000: 0
screenWidth must be greater than 1 and less than 1000000000: 0
screenHeight must be greater than 1 and less than 1000000000: 0

### Log files

http://www.liuwenxian.info:5000/vr/%E8%B5%84%E6%96%99%E5%A4%87%E4%BB%BD/latest.log

**Comment by henkelmax** [comment]
I won't click at unknown links. Please use a site like github gist or mclo.gs to upload logs.
Which OS are you using?
