### ISSUE TITLE
GUI Issue W/optifine 

### ISSUE THREAD

**Issue by ItsNiyaz** [henkelmax/camera#11]
Hello,

So my friend and I downloaded this mod for our server, now for some reason when he joined, he was not able to view his hotbar, chat, inventory or any sort of GUI (besides the journey map on top of his screen)

We realised that this was because optifine was clashing with the camera mod for some reason and we have no clue on why. We’ve had to remove this mod because he prefers to have optifine but I was really hoping we could somehow come to figure out a solution so I can get the camera mod can on our server again.

**Comment by henkelmax** [comment]
This is a known issue, but I can't debug my mod with OptiFine, because it's not open source and they don't provide a deobfuscated version.
Please report this issue to the OptiFine issue tracker. Maybe they find the issue, but I can't do anything about it.
