### ISSUE TITLE
Client crash on login (Sponge)

### ISSUE THREAD

**Issue by Druwan-ctrl** [henkelmax/camera#12]
**Bug description**
If i'm not mistaken it seems like the mod looks for files in the wrong directory, in ./world while the picture exists in ./world/flat

**Steps to reproduce the issue**
1. Connect to the server
2. The chunks starts loading
3. Disconnected

**Expected behavior**
Just log in

**Log files**
my friend's log: https://gist.github.com/Druwan-ctrl/9c90fbb26bf1ea066600f34154fc8677
my log: https://gist.github.com/Druwan-ctrl/9f0749734ce6ccf2b2d4aab2adad6566

**Versions**
- Minecraft version 1.12.2
- Forge version 1.12.2-forge-14.23.5.2854
- Mod version camera-1.0.10

**Other mods**
Major suspect: sponge or it's plugin nucleus, since it manages worlds, the other mods are:
AdditionalBanners-1.12.2-1.1.77.jar
additional_lights-1.12.2-1.2.1.jar
AIImprovements-1.12.1-0.0.1b1.jar
AmbientEnvironment-1.0.2.jar
AppleSkin-mc1.12-1.0.14.jar
Aquaculture-1.12.2-1.6.8.jar
astikorcarts-1.12.2-0.1.2.7.jar
AttributeFix-1.12.2-1.0.4.jar
AutoRegLib-1.3-32.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
betterchat-1.4.jar
BetterFoliage-MC1.12-2.3.1.jar
BetterPingDisplay-1.12.2-1.0.jar
biolib-1.1.1.jar
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
BNBGamingCore-1.12.2-0.12.0.jar
BNBGamingLib-1.12.2-2.17.6.jar
Bookshelf-1.12.2-2.3.590.jar
BuildingGadgets-2.8.4.jar
callablehorses-1.12.2-1.1.jar
camera-1.0.10.jar
Chameleon-1.12-4.1.3.jar
ChanceCubes-1.12.2-5.0.2.385.jar
Chisel-MC1.12.2-1.0.2.45.jar
ChunkAnimator-MC1.12-1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
conarm-1.12.2-1.2.5.9.jar
Controlling-3.0.10.jar
CookingForBlockheads_1.12.2-6.5.0.jar
cosmeticbeds-1.12.2-1.0.2.2.jar
CraftPresence-Forge-1.12.2-Release-1.7.5.jar
CraftTweaker2-1.12-4.1.20.586 (1).jar
CreativeCore_v1.10.34_mc1.12.2.jar
CTM-MC1.12.2-1.0.2.31.jar
CustomNPCs_1.12.2-(05Jul20).jar
despawningspawners-1.12-1.2.0-2.jar
DimensionStages-1.12.2-2.0.23.jar
DocumentYourModMod-2.0.2.jar
Dungeons2-mc1.12.2-f14.23.5.2768-v1.7.5.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
Earthworks-1.12-1.3.6.jar
ElenaiDodge-1.12.2-1.12.0.jar
Emojicord-1.12.2-1.1.1.39-universal.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
EndReborn [0.3.9].jar
ep_1.12-1.0.jar
EquipmentTooltips-1.12.2-1.0.3-4.jar
FallingTree-1.12.2-2.4.0.jar
FarmingForBlockheads_1.12.2-3.1.28.jar
FastWorkbench-1.12.2-1.7.3.jar
ffenchants-1.12.2-1.1.5.jar
Fish's Undead Rising-1.2.3.jar
foamfix-0.10.10-1.12.2.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
FpsReducer-mc1.12.2-1.18.jar
FriendlyFire-1.12.2-1.5.10.jar
from_the_depths-1.2.1.0.jar
FullscreenWindowed-1.12-1.6.0.jar
future-mc-1.12.2-0.2.4.1.jar
gamestagebooks-1.12.2-1.0.2-universal.jar
GameStages-1.12.2-2.0.123.jar
gamestagesviewer-1.0.jar
GiacomosBookshelf-1.12.2-1.2.jar
GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar
HappyTrails-1.12.2-1.0.0.5.jar
Headcrumbs-1.12.2-2.0.5.17.jar
heroicarmory-1.2.0.jar
horsestandstill-1.12.2-0.0.1.jar
hunterillager-1.12.2-1.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
ido-1.12.2-1.1.0.jar
ImprovedBackpacks-1.12.2-1.5.0.0.jar
incontrol-1.12-3.9.18.jar
Infinity-0.14.2.jar
InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.72.847.jar
ItemStages-1.12.2-2.0.49.jar
jeiintegration_1.12.2-1.6.0.jar
jei_1.12.2-4.16.1.301.jar
jepb-1.12-1.2.1.jar
JJ+Races+1.12-1.12.2-v1.0.14.jar
jmh_1.12-2.1.jar
journeymap-1.12.2-5.5.4.jar
JourneyMapStages-1.12.2-2.0.9.jar
jph_1.12-1.0.jar
just-enough-brewcraft-1.12.2-1.0.2.jar
just-enough-harvestcraft-1.12.2-1.7.2.jar
kinetic_anti-cheat-12.2.2.jar
LetSleepingDogsLie-1.12.2-1.0.2.jar
levelup2-1.5.8.jar
LibraryEx-1.12.2-1.2.0.jar
living_enchantment-3.2.3.jar
llibrary-1.7.20-1.12.2.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
MagmaMonsters-0.3.0.jar
Mantle-1.12-1.3.3.55.jar
MCDJ-1.12.2-2.1.jar
Metallurgy-4-Reforged-1.2.0.jar
mightyarchitect-0.3.0.jar
MmmMmmMmmMmm-1.12-1.14.jar
MoarSigns-1.12.2-6.0.0.11.jar
mountedpearl-1.12.2-0.0.1.jar
mowziesmobs-1.5.8.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
multimob-1.0.5.jar
MutantBeasts-1.12.2-1.0.1.jar
naturalbabyanimals-1.2.2-mc1.12.x.jar
naturalnetherportals-1.2.0-mc1.12.x.jar
NetherEx-1.12.2-2.2.0.jar
nethergoldore-1.2.1-mc1.12.x.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
OldJavaWarning-1.12.2-1.1.11.jar
OptiFine_1.12.2_HD_U_F5.jar
ordinarycoins-1.12.2-1.5.jar
OreLib-1.12.2-3.6.0.1.jar
overloadedarmorbar-1.0.4g.jar
Pam's+BrewCraft+1.12.2-1.0.2.jar
Pam's+HarvestCraft+1.12.2zg.jar
Patchouli-1.0-22.jar
pigstep-1.12.jar
potiondescriptions-1.12.2-1.2.3.jar
primitivemobs-1.2.3a.jar
ProgressiveBosses-1.5.4-mc1.12.x.jar
ProjectRed-1.12.2-4.9.4.120-Base.jar
ProjectRed-1.12.2-4.9.4.120-compat.jar
ProjectRed-1.12.2-4.9.4.120-integration.jar
ProjectRed-1.12.2-4.9.4.120-lighting.jar
ProjectVibrantJourneys-1.12.2-1.6.4.jar
Quark-r1.6-179.jar
QuarkOddities-1.12.2.jar
questbook-3.0.0-1.7.10.jar
randompatches-1.12.2-1.22.1.9.jar
RecipeStages-1.1.3.jar
ResourceLoader-MC1.12.1-1.5.3.jar
Ruins-1.12.2.jar
rustic-1.1.7.jar
scarper-1.1.jar
Schematica-1.12.2-1.8.0.169-universal.jar
ServerTabInfo-1.12.2-1.2.6.jar
simpletrophies-1.2.2.1.jar
SmoothFont-mc1.12.2-2.1.2.jar
SoundFilters-0.12_for_1.12.jar
Stackie-1.12.2-1.6.0.48-universal.jar
StorageDrawers-1.12.2-5.4.2.jar
structurize-1.12.2-0.10.277-RELEASE.jar
swingtg-1.12.2-1.2.3.jar
TConstruct-1.12.2-2.13.0.183.jar
thesummoner-1.0.1.jar
tinkersjei-1.2.jar
TinkerStages-1.12.2-2.0.15.jar
tinkers_reforged-1.4.1.jar
Tips-1.12.2-1.0.9.jar
Titles-1.12.2-3.1.6.jar
torchmaster_1.12.2-1.8.4.84.jar
torchslabmod-1.12.2-v1.5.2.jar
toughnessbar-2.4.jar
TrashSlot_1.12.2-8.4.10.jar
Treasure2-mc1.12.2-f14.23.5.2768-v1.13.1.jar
Triumph-1.12.2-3.19.2.jar
tweakersconstruct-1.12.2-1.5.5.jar
twilightforest-1.12.2-3.11.1021-universal.jar
Uppers-0.0.6.jar
villagerdeathm_1.12-1.2.jar
Waddles-1.12.2-0.6.0.jar
WailaHarvestability-mc1.12-1.1.12.jar
WailaStages-1.12.2-2.0.23.jar
walljump-1.12.2-1.3.2.jar
Waystones_1.12.2-4.1.0.jar
wolfarmor-1.12.2-3.7.5-universal-signed.jar
WorldEdit-CUI-FE3-1.12.2-3.0.8.jar
xptome-1.12.2-v1.1.6.jar
zenstages-0.5.0.jar
[1.12][Forge]+RPG-HUD-3.8.1.jar

**Comment by henkelmax** [comment]
I can't see any crash that is related to the camera mod in your logs.

> If i'm not mistaken it seems like the mod looks for files in the wrong directory, in ./world while the picture exists in ./world/flat

If this would be true, it would crash the server, because the client does not save any images.
If your server throws any camera mod related errors, please send me the logs of your server.

I also can't promise if I fix this issue if it is specifically related to sponge as it breaks forge mods very often.

**Comment by Druwan-ctrl** [comment]
Thank you for the fast reply! It seems i uploaded the wrong file, in mine you can't see the error, it's not even logged, my friend could log that line before the disconnect (which didn't create a crash report). Meanwhile removing the camera mod solved the issue, will try to give you the correct file as soon as i can

**Comment by henkelmax** [comment]
> Edit: the server is fine because it was the client that tried to search in the wrong directory, but the server still has them in the correct folder

What do you mean with "tried to search in the wrong directory"?

**Comment by Druwan-ctrl** [comment]
Sorry if I still reply without the proper log, I didn't have the chance to get it. From what I seen our clients searchet for a photo that i took in the flat world, that's in ./world/flat, but it tried yo load it from ./world, so it couldn't render it and caused an instant disconnection without any error

**Comment by henkelmax** [comment]
Can you send me the log of this crash?

**Comment by henkelmax** [comment]
Closed due to inactivity
