### ISSUE TITLE
GUI Item "Image" not showing

### ISSUE THREAD

**Issue by sheloves-e** [henkelmax/camera#13]
Hello, so I use Optifine just in case thats important information, apart from that i do not use teture packs of any sort. For some reason, the image item doesnt show in the Inventory, when you hover over it, you can read "Image" and of course taken by on... You know the drill, but the item is invisible, you can still put it in frames, see it and everything. Just not in inventory.

**Comment by henkelmax** [comment]
This is a known issue with optifine. Please report this to the optifine issue tracker.
