### ISSUE TITLE
1.12.2 Camera filter don't work :/

### ISSUE THREAD

**Issue by I3estOFF** [henkelmax/camera#14]
**Bug description**
Can't change filter!
This is great mod! I want to use it in my modpack, my fav filter is Sepia but i can't change it!
Am i doing something wrong or is it a bug?

**Steps to reproduce the issue**
1. Go to minecraft world
2. Shift-right click on Camera
3. Change filter
4. Nothing changed!

**Expected behavior**
Changing Camera filter

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- 1.12.2
- 14.23.5.2854
- camera-1.0.10

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/63112899/106609422-d388eb00-6565-11eb-8424-4730468ae432.png)

**Comment by henkelmax** [comment]
Please fill out the complete bug template. Also don't forget to provide logs and a video of the problem.

**Comment by I3estOFF** [comment]
VIDEO
[2021-02-02 15-10-39.zip](https://github.com/henkelmax/camera/files/5911692/2021-02-02.15-10-39.zip)

**Comment by henkelmax** [comment]
Is this happening without other mods installed?
If not please check what mod causes this.

**Comment by I3estOFF** [comment]
260 mods installed
Thats impossible to me which mod can do this. 
Shouldn't be a accept button in filters section?

**Comment by henkelmax** [comment]
That's totally possible. Just remove half of the mods and check if it still occurs. Repeat this until just one is left.

**Comment by I3estOFF** [comment]
Latest log

[latest.log](https://github.com/henkelmax/camera/files/5911909/latest.log)

**Comment by I3estOFF** [comment]
im searching, one of the mods causing this

**Comment by I3estOFF** [comment]
OptiFine_1.12.2_HD_U_F5

**Comment by henkelmax** [comment]
This is a known issue. You can report it to their issue tracker, but I don't think they are gonna fix it.

**Comment by I3estOFF** [comment]
omg so many hours for nothing ;-;

**Comment by I3estOFF** [comment]
i repaired it

**Comment by I3estOFF** [comment]
now it's working with optifine

**Comment by henkelmax** [comment]
How?

**Comment by I3estOFF** [comment]
Turn off Fast Render

**Comment by henkelmax** [comment]
Oh, OK. Thanks for letting me know!
