### ISSUE TITLE
Breaking frame does not return picture

### ISSUE THREAD

**Issue by V2LenKagamine** [henkelmax/camera#17]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
See title
"Breaking a Frame does not return the picture within it,"

**Steps to reproduce the issue**
Place Picture In frame
Resize picture(Optional)
Get no picture back

**Expected behavior**
The picture to be returned as it was before being put in the frame

**Log files**
No notable logs generate server side

**Versions**
- Minecraft version:1.16.5
- Forge version:36.0.42
- Mod version: 1.0.5

**Other mods**
None

**Comment by henkelmax** [comment]
Thank you for reporting this issue! It should be up on CurseForge very soon. Let me know if it works for you.
