### ISSUE TITLE
game crash 1.15.2

### ISSUE THREAD

**Issue by thefoodunicorn** [henkelmax/camera#18]
**Bug description**
This bug happens what I try and upload a photo on any 1.15.2 version of this mod

**Steps to reproduce the issue**
1. open game with mod installed
2.press upload photo button
3. the game crashes 
**Expected behavior**
I expected the mod too work it docent only with 1.16.4 

**Log files**
I don't know how to paste the log file here but the issue seems to be with java since it says java quit unexpectedly 

**Versions**
- Minecraft version 1.15.2
- Forge version 31.2.0
- Mod version tried with multiple versions even the newest does it
- iOS version Mac OS Catalina 10.15.6
**Other mods**
tested with other mods and standalone

please fix this issue asap as I need this mod for 1.15.2 (all my other mods are for that version)

**Comment by henkelmax** [comment]
Thanks for reporting this issue. Should be fixed in the next version.
