### ISSUE TITLE
[suggestions] Image frame protection

### ISSUE THREAD

**Issue by Daejangnamu** [henkelmax/camera#2]
1.16.2
Please add a feature to prevent others from destroying the image frame.
It would be great if only the creator of the image frame could interact.

**Comment by henkelmax** [comment]
Thank you for suggesting this feature.
You can enable it in the server config.

But keep in mind that pushing a block into the frame with a piston breaks the frame.

**Comment by Daejangnamu** [comment]
> 이 기능을 제안 해 주셔서 감사합니다.
> 서버 구성에서 활성화 할 수 있습니다.
> 
> 그러나 피스톤으로 블록을 프레임에 밀어 넣으면 프레임이 파손됩니다.

Thanks for the update.

**Comment by henkelmax** [comment]
No problem!
