### ISSUE TITLE
Pictures can't be placed on lecterns

### ISSUE THREAD

**Issue by stanlabs** [henkelmax/camera#20]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
The bug is you can't place an image onto an lectern as mentioned in the mod description 
**Steps to reproduce the issue**
1. Go to the latest version of forge with the latest mod
2. Click on a lectern with a image
3. See error

**Expected behavior**
The image can't be placed
**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 16.5
- Forge version Latest 16.5
- Mod version The latest 16.5

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
You can only place albums in lecterns. Images alone wouldn't make much sense.

**Comment by stanlabs** [comment]
alright, it just said it in the description and i wanted to use it to put decorative engineer blueprints on it![image](https://user-images.githubusercontent.com/75456944/116025775-4b275d00-a61f-11eb-84a3-b315816fd288.jpeg)

**Comment by henkelmax** [comment]
Just put the image into the album and then into the lectern.
