### ISSUE TITLE
Crash on startup in 1.16.5-1.0.11

### ISSUE THREAD

**Issue by relsqui** [henkelmax/camera#22]
**Bug description**
Forge loader crashes during initialization.

**Steps to reproduce the issue**
1. Add only camera mod to a fresh profile in the curseforge desktop app
2. Start it

**Log files**
[latest.log](https://github.com/henkelmax/camera/files/6410714/latest.log)

**Versions**
- Minecraft version 1.16.5
- Forge version 36.1.16
- Mod version 1.16.5-1.0.11

**Other mods**
Saw this first in a pack with ~150 other mods but was able to reproduce with only this one.

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.

**Comment by relsqui** [comment]
Thanks!
