### ISSUE TITLE
Feature request: tripod

### ISSUE THREAD

**Issue by relsqui** [henkelmax/camera#23]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to take pictures of my builds or my play group that have my own character in them.

**Describe the solution you'd like**
I'm imagining a tripod as a block I can craft, place, and then put my camera on. When the tripod receives a redstone pulse, it takes a photo (which could either drop into the world or have a storage space in the tripod block).

**Describe alternatives you've considered**
I can take screenshots in third person mode but it's more awkward to use and not the same. 

**Additional context**
This would also be fun for base security and wildlife photography. (Also: I enjoy this mod so much that I built a gallery on a multiplayer server so I could display my favorite shots. Thanks for making it!)

**Comment by henkelmax** [comment]
I'm sorry, but due to technical limitations it it not possible.

**Comment by relsqui** [comment]
Ah too bad, thanks for the quick answer. :)
