### ISSUE TITLE
Image Frame not protected by Plugins

### ISSUE THREAD

**Issue by Matthysse** [henkelmax/camera#24]
Hello !

I know it's a weird issue, and mods aren't normally supposed to be compatible with plugins, but it would be nice if you could fix this little bug:
I'm using Arclight (a Bukkit+Forge implementation) with the WorldGuard plugin. It works really great, and it really protects and entities from all mods. The only thing is that players can destroy image frames in protected areas, unlike item frames, paintings and other entities from other mods (but placing an image frame is impossible in protected areas). Seems therefore that the action of destroying the image frame isn't considered by the server as made by the player. Would be nice if it could be the case!

**Comment by henkelmax** [comment]
I'm sorry, but I don't support plugins.
