### ISSUE TITLE
Transparency for uploaded images

### ISSUE THREAD

**Issue by Matthysse** [henkelmax/camera#25]
Hello!

It would be nice if you could make that uploaded images can be transparent. Currently, if you try to place an uploaded image with transparency, it just gets a black background. Just like the transparent paintings in vanilla with ressource packs, if we could place images with transparency, it would allow us to be more creative in the way we place it, and to keep the texture of the block that is behind the frame.

**Comment by henkelmax** [comment]
Unfortunately, this is not possible, due to the rendering of the edges of the frame.
