### ISSUE TITLE
Re: Image Frames not supported in protected areas.

### ISSUE THREAD

**Issue by Matthysse** [henkelmax/camera#26]
Hello again,

It's me from the issue you just closed https://github.com/henkelmax/camera/issues/24
I just want to say that it's not only for plugins, but I'm sure it's a problem for area-protecting mods like FTB-Teams or Forge Essentials. In both cases, if you don't flag the removal of the image frame by the player, it will create incompatibilities, even with mods. It would be very useful if you could patch this problem. I love your mod and it really allows us to be creative and to share experiences with other players, but if they just can destroy it and put it in lava, you destroy memories.

**Comment by henkelmax** [comment]
I don't intend to add compatibility with any land protecting mods or plugins. If it doesn't work with the FTB mods, report it on their issue tracker.
