### ISSUE TITLE
Can't Upload Custom Image on Linux (Debian Ubuntu Distro)

### ISSUE THREAD

**Issue by Santeeag0** [henkelmax/camera#30]
_**Bug description**_
When Sneak Right Clicking with the Camera and Clicking Upload Image Nothing Happens 

_**Steps to reproduce the issue**_
1. Go to 'Sneak Right Click Camera'
2. Click on 'Upload Image'
4. Nothing Happens

**_Expected behavior_**
I've used this mod on windows and it opens the file explorer as expected, but on my Linux system I'm not prompted with anything to allow me to upload my custom image. 

**Log files**

_**Versions**_
- Minecraft version: 1.16.5
- Forge version: 36.2.2
- Mod version: Camera Mod 1.16.5-1.0.14

**Other mods**

**Screenshots (Optional)**

**Comment by henkelmax** [comment]
I need your logs.

**Comment by Santeeag0** [comment]
> I need your logs.

Not at my main computer at the moment but ill upload them when i get back to it. Which logs to be specific? Just to make sure im giving the information you need.

**Comment by henkelmax** [comment]
`.minecraft/logs/latest.log`

**Comment by Santeeag0** [comment]
> .minecraft/logs/latest.log

Okay ill upload them as soon as i get home thank you!

**Comment by Santeeag0** [comment]
Here is my Latest.log File https://gist.github.com/Santeeag0/887a562af68b614731e57f54250ba100

**Comment by henkelmax** [comment]
Can you reproduce this issue without any other mods and send me the logs of that please?

**Comment by Santeeag0** [comment]
> Can you reproduce this issue without any other mods and send me the logs of that please?

Yes i can, I’ll upload the log once i do so.

**Comment by Santeeag0** [comment]
Latest.log https://gist.github.com/Santeeag0/b22e4747ef8e5dddb9c3cabab2e01f92

https://user-images.githubusercontent.com/84484542/131969469-d8ceeef8-7239-482e-8e9c-67c6b1195296.mp4

**Comment by henkelmax** [comment]
I am not able to reproduce this issue (Haven't tried ubuntu specifically).

Does this happen without any other mods?
Can you try it with the vanilla minecraft launcher?
Are you using wayland?

**Comment by Santeeag0** [comment]
Yes it happens with only the Camera Mod Installed. I can, I used gdlauncher for those logs so Ill try out the vanilla launcher, Pretty sure wayland is disabled by default on my os (popos)

**Comment by Santeeag0** [comment]
Also if you cant figure it out or is too much of a hassle its fine I definitely understand I love the mod and the work you’ve put into it! If anything i can just use a windows machine and upload my custome image from there lol

**Comment by Santeeag0** [comment]
I was not able to figure out how to get forge installed to the vanilla launcher so I couldnt test it.

**Comment by Bimi124** [comment]
I am using Ubuntu and uploading works for me (Tested with Unity Desktop Manager)

**Comment by henkelmax** [comment]
> I am using Ubuntu and uploading works for me (Tested with Unity Desktop Manager)

Alright, thanks for letting me know.
