### ISSUE TITLE
Glitch with Rats mod

### ISSUE THREAD

**Issue by mxnmnm** [henkelmax/camera#36]
**Bug description**
Whenever you give yourself the synesthesia effect with this mod installed, things glitch out.

**Steps to reproduce the issue**
1. Install the Rats mod and this mod
2. Give yourself the synesthesia effect
3. Enjoy the view 

**Expected behavior**
For the screen to not flicker violently, and for the synesthesia effect to look normal.

**Log files**
https://gist.github.com/mxnmnm/67a5bd766e0f006bb400eb898ff2dd55

**Versions**
- Minecraft version: 1.12.2
- Forge version: 14.23.5.2855
- Mod version: 1.0.11

**Other mods**
Rats

**Comment by henkelmax** [comment]
1.12.2 is no longer supported.
