### ISSUE TITLE
Images are not being returned when right clicking the frame. They disappear.

### ISSUE THREAD

**Issue by Alriac** [henkelmax/camera#38]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
Images are not being returned when right clicking the frame with an empty hand, they just disappear, after appearing for a brief moment on your hotbar. But you can always get the image back with left click, since it drops to the world instead of your inventory.
The images still exist in the filesystem, just there is no item for them.

**Steps to reproduce the issue**
1. Take a picture and put it on a frame of any size.
2. Right click the picture on the frame with an empty hand.
3. Image appears briefly on your active hotbar slot before going missing forever.

**Expected behavior**
You get the image item on the active hotbar slot and can use it again.

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.16.5
- 36.2.8
- 1.0.14

**Other mods**
Valhelsia 3 modpack (added this mod later, was not included)
Only tested in multiplayer.

**Comment by henkelmax** [comment]
Does this also happen in newer Minecraft versions?

**Comment by henkelmax** [comment]
Closed due to inactivity
