### ISSUE TITLE
Crash when attempting to save NBT on PlayerEntity

### ISSUE THREAD

**Issue by arketec** [henkelmax/camera#39]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
Game crashes when trying to save NBT. Only occurs with this mod added to my pack

**Steps to reproduce the issue**
go away from loaded area and come back or hit ESC in SMP 

**Expected behavior**
Expected NBT data to save correctly

**Log files**
https://pastebin.com/fbVg6085

**Versions**
- Minecraft version 1.18.1
- Forge version 30.0.6
- Mod version 1.18.1-1.0.0

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.
https://pastebin.com/L16gB2Z4

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I can't confirm this issue. 

> A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

Please do what's in the template.

**Comment by arketec** [comment]
I already spent 2 hours narrowing it down to your mod. Im not willing to spend any more time. This was a report for your benefit, spending time going mod by mod isn't something I'm interested in, I'll just uninstall this mod and not worry about it

**Comment by henkelmax** [comment]
I can't help you if I can't reproduce the issue, sorry.

**Comment by arketec** [comment]
understandable, I just figured a bug report is better than no bug report. If I feel like taking on the testing load, Ill submit again with more details.
