### ISSUE TITLE
Game Crashes when clicking upload photo

### ISSUE THREAD

**Issue by draklorx** [henkelmax/camera#4]
**Bug description**
When I click upload from the camera interface the client crashes.

**Steps to reproduce the issue**
1. Shift click to open camera interface
2. Click on upload
3. Game crashes

**Expected behavior**
Prompts me to upload an image.

**Log files**
Crash Log
https://gist.github.com/draklorx/0888964dd2565d0593063ee4866b0288

**Versions**
- Minecraft version: 1.16.1
- Forge version: 32.0.108 
- Mod version: camera-1.16.1-1.0.7

**Other mods**
I removed all other mods and retested and the error persisted (though this was on the local world and not on a remote server)

**Screenshots (Optional)**
https://imgur.com/a/GFMuB5b

**Comment by draklorx** [comment]
Let me know if I can provide any more details! I'm happy to help however I can!

**Comment by henkelmax** [comment]
What java are you using(OpenJDK, Oracle JDK, ...)?

**Comment by henkelmax** [comment]
It seems that you are using OpenJDK. This feature unfortunately only works with the Oracle Java.
