### ISSUE TITLE
Lectern Mixin adds NBT to the EMPTY stack

### ISSUE THREAD

**Issue by Buuz135** [henkelmax/camera#40]
When a lectern is loaded (from a village for a example) the `ItemStack.EMPTY` gets the `image` NBT, probably cause by this https://github.com/henkelmax/camera/blob/master/src/main/java/de/maxhenkel/camera/mixins/LecternTileEntityMixin.java#L88

It might also happen in the other methods.

**Versions**
- Minecraft version: 1.18
- Forge version: 39.0.09
- Mod version: 1.0.0

**Comment by henkelmax** [comment]
Thanks for reporting this issue!
I additionally added some asserts, so this hopefully won't happen again.

**Comment by sfPlayer1** [comment]
It is also highly advisable to avoid `getOrCreateTag()` for operations without write/mutation intent like in https://github.com/henkelmax/camera/blob/064d756281b31726e3166031e8fbeb4b6a1280f3/src/main/java/de/maxhenkel/camera/ImageData.java#L145 and instead use getTag and check the result for null.

**Comment by henkelmax** [comment]
It is used to modify the tag in most cases.
