### ISSUE TITLE
Issues with JEI when playing in multiplayer

### ISSUE THREAD

**Issue by Slegan66** [henkelmax/camera#42]
**Bug description**

When my friend attempts to join my server, they time out, when checking their log I saw errors/warnings mentioning Camera, and upon further testing narrowed it down to JEI and Camera that was breaking.

When JEI and Camera are both enabled, JEI on the clients side seems to be finding a recipe that requires "minecraft:air" to make, and it really does not like that. This does not happen on the servers side, which is strange.

When we remove Camera, they do not get the error.
When we remove any recipe browser mod while Camera is in the mod folder, they do not get the error.
I tested to see if it works with another recipe browser, "Roughly Enough Items," with a similar result.

**Steps to reproduce the issue**
1. Host a server with JEI and Camera enabled
2. Have a player with those two mods join
3. Client's game will time out, check logs

**Expected behavior**
Server owner may see player in frozen state after joining, not moving after being hit. Joining player may not see anything load in and then time out.

**Log files**
I need some time to reobtain the logs, I only took note of the important parts so I apologize.

Whenever my friend tries to join my server he times out, and gets the following error in his log:

[1822022 22:33:21.038] [main/ERROR] [mezz.jei.recipes.RecipeManagerInternal/]: Found a broken recipe: 1 air
Outputs: net.minecraft.item.ItemStack: [[1 image camera:image]]
Inputs: net.minecraft.item.ItemStack: [[1 air minecraft:air]]

Server side, in my log I get:

[18Feb2022 23:10:56.994] [main/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] FriendsUsername joined the game
[18Feb2022 23:11:26.119] [main/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: camera:default
[18Feb2022 23:11:26.125] [main/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Unknown custom packet identifier: camera:default
[18Feb2022 23:11:34.817] [Server thread/INFO] [net.minecraft.network.play.ServerPlayNetHandler/]: FriendsUsername lost connection: Disconnected

**Versions**
Minecraft version: 1.16.6
Forge version: 36.2.37
Mod version: 1.0.14

**Other mods**
AI Improvements
Biomes You'll Go
ComputerCraft Tweaked
Clumps
ExtremeReactors2
FastSuite
FerriteCore
FPS-Reducer Forge
IronChest
Just Enough Items - The one that is breaking
Mekanism - All four components
Optifine - Other player was using Magnesium.
Patchouli
Placebo
TouhouLittleMaid
ZeroCore2

I determined it was JEI/Camera that was breaking by adding mods until my friend was unable to join and then checking logs, so I did not test it with only JEI and Camera and currently am not able to do so.

**Comment by henkelmax** [comment]
Please post the full logs with github gist, like diescribed in the template.

**Comment by Slegan66** [comment]
I meant 1.16.5, but my keyboard is small so I hit six instead.

Here are the logs.

[latest server.log](https://github.com/henkelmax/camera/files/8104670/latest.server.log)
[latest client.log](https://github.com/henkelmax/camera/files/8104671/latest.client.log)

**Comment by henkelmax** [comment]
Can you send me your camera mod server config file?

**Comment by Slegan66** [comment]
I don't have a config that explicitly says "server," probably because I am just hosting to LAN, but it should be using this one. I wiped the config folder multiple times while trying to fix it myself so this should be the default.

[camera-client.toml.txt](https://github.com/henkelmax/camera/files/8111053/camera-client.toml.txt)

**Comment by henkelmax** [comment]
> I don't have a config that explicitly says "server," probably because I am just hosting to LAN, but it should be using this one. I wiped the config folder multiple times while trying to fix it myself so this should be the default.
> 
> [camera-client.toml.txt](https://github.com/henkelmax/camera/files/8111053/camera-client.toml.txt)

Thats the client config. The server config is in the world folder.

**Comment by Slegan66** [comment]
My bad, here is the server config though.

[camera-server.toml.txt](https://github.com/henkelmax/camera/files/8111088/camera-server.toml.txt)

**Comment by henkelmax** [comment]
I'm gonna close this, as it doesn't seem to happen in newer versions.
