### ISSUE TITLE
Png v Jpeg or config option to disable all compression

### ISSUE THREAD

**Issue by ImZelleDuh** [henkelmax/camera#49]
**Is your feature request related to a problem? Please describe.**
When editing the server config file compression value to the upper limit as to have the least amount of compression the iamges still get compressed to a point where they dont look as clean as what im looking at infront of me in game.

Camera-server.toml
19-20
When setting line 20 to 1.0 it doesnt compression the image as much but compression still occurs

I have set line 16
Max_size to 999999
So line 18 saying if it exceeds max_image_size it will get compressed anyways should not take effect. However the images still undergo some amount of compression.

**Describe the solution you'd like**
2 solutions
1. A config option preferably in the client config as to not have to edit it per world like with the server config that allows the image type to be saved as a png and not a jpeg

2. A client config option that allows you to disable compression

If it cant be made into a client config option then a server config option is perfectly fine.

**Describe alternatives you've considered**
I dont know of any alternative solutions for this issue.

**Additional context**
It would be nice to use this image saves as thumbnails for youtube videos however currently i would have to take a pic in game to save to my album and a pic with f2 to get a higher quality pic. However i wouldnt be able you use your filters with that method so higher quality images would solve that. Having the option for higher quality images would also make looking back at the photo album more enjoyable since the pics would be more pleasing to look at.

**Some extra notes**
If removing compression or changing the file type increases the file size of images by a large amount it would be nice to have a config option to change the file path that the images get saved to as to save them to my hard drive instead of my ssd. If the above requests get put through and this does become a problem i will open a new issue ticket for this request.

**Comment by henkelmax** [comment]
This compression must be done, since the data needs to be sent via minecrafts networking, which is not designed to transfer bigger amounts of data.
Despite this limitation, sending multiple split packets causes the networking of minecraft to hang and cause lag.
Also when you are looking at an album full of images, the game would hang for a minute until all images would be synced.
Its simply not possible to send bigger images.

**Comment by ImZelleDuh** [comment]
Ok didnt know that thank you for the clarification.
