### ISSUE TITLE
Client crash when use Shift + Right Click.

### ISSUE THREAD

**Issue by PabloAlbu** [henkelmax/camera#54]
**Bug description**
When I try to upload an image with shift + right click the game crashes.

**Log files**

https://gist.github.com/PabloAlbu/546c8431a1a264c0f0de7d579ce6f67f

**Versions**
- Minecraft version: 1.18.2
- Forge version: 40.1.76
- Mod version: camera-1.18.2-1.0.4

**Comment by henkelmax** [comment]
Can you please send me your full logs?

**Comment by henkelmax** [comment]
Please also send me your server config.

**Comment by henkelmax** [comment]
Nevermind, I found the issue.

**Comment by PabloAlbu** [comment]
Now work perfect. Thank you so much!!!
