### ISSUE TITLE
Render Error

### ISSUE THREAD

**Issue by ImBlazeVT** [henkelmax/camera#57]
When I take a picture, my client shows this error, next, the server/world closes and send me to the tittle menu

**Versions**
- 1.19
- 41.1.0
- 1.19-1.0.6

![Captura de pantalla (1341)](https://user-images.githubusercontent.com/113817898/190887820-75988d07-e5ea-46ab-b8da-f6e77d94f9b2.png)

**Comment by henkelmax** [comment]
Please provide the logs like described in the template

**Comment by henkelmax** [comment]
Please also update to 1.19.2. We only support the latest patch of a release.

**Comment by henkelmax** [comment]
Closed due to inactivity.
