### ISSUE TITLE
Uploaded Frames disappears randomly 

### ISSUE THREAD

**Issue by Axelouuu-dev** [henkelmax/camera#59]
**Bug description**
Uploaded frames disappears sometimes when I click on image frame the photo didn't drop or when I reconnect to the server the photo has disappears from the wall. 

**Log files**
In log file, it can be read some packet errors at ligne from 4805 to 4811 :
`Unknown custom packet identifier: camera:default`
[latest.log](https://github.com/henkelmax/camera/files/9879808/latest.log)

**Versions**
- Minecraft version : 1.18.2
- Forge version : 40.1.80
- Mod version : 1.0.5

**Comment by henkelmax** [comment]
> In log file, it can be read some packet errors at ligne from 4805 to 4811 :
Unknown custom packet identifier: camera:default

These messages are completely normal.

I can't see any errors about the mod in your logs.
Can you please send me a video of this issue?

**Comment by Axelouuu-dev** [comment]
Thanks for reply.

Okey so there a video :
https://user-images.githubusercontent.com/19538750/198684806-55c8d0f1-8332-4b00-9734-0a63e1e245ec.MP4

The problem seems appear when another player try to get an uploaded photo.

**Comment by henkelmax** [comment]
Was this person in creative mode?
Did you check if this issue occurs above ground?
The item might have glitched into the wall.

**Comment by Axelouuu-dev** [comment]
There is nobody in creative mode and and the item was never found.

**Comment by henkelmax** [comment]
Please check it again in an open space

**Comment by henkelmax** [comment]
I just tested it on a server, exactly the way you did in your video and it works perfectly fine.

**Comment by Axelouuu-dev** [comment]
On the first video my friend right click on the uploaded photo for get it to his hand and drop it.
I make another video where it's me to reproduce the bug : 

https://user-images.githubusercontent.com/19538750/200390148-c966586e-1f5a-47c4-be71-2eefebef5fd2.mp4

I upload a picture, put it to frame, right click on it to get it (it appear in my hand but other players doesn't see it) and when I drop item or open my inventory, the photo is nowhere.

**Comment by henkelmax** [comment]
https://user-images.githubusercontent.com/13237524/200391666-64842af3-66ae-4f6f-ba57-8c6baf283a32.mp4

**Comment by Axelouuu-dev** [comment]
Is that an uploaded photo from computer ?

**Comment by henkelmax** [comment]
https://user-images.githubusercontent.com/13237524/200393721-9d9d63d1-7808-45af-971d-64f569800ffc.mp4

Same with uploaded images

**Comment by Axelouuu-dev** [comment]
Okey, it's strange 🤔
Sorry for the inconvenience 😶‍🌫️ and thanks for your time 😇
