### ISSUE TITLE
Upload multiple images at once

### ISSUE THREAD

**Issue by vvbv** [henkelmax/camera#61]
Is your feature request related to a problem? No

Describe the solution you'd like
It would be nice if the window to select the images allows you to select several at the same time.

Going through the code a bit, I found that the allow multiple selects flag is allowed, and it admits values of 0 and 1
```
char * tinyfd_openFileDialog(
	...
	int aAllowMultipleSelects ) ; /* 0 or 1 */
		/* in case of multiple files, the separator is | */
		/* returns NULL on cancel */
```
https://github.com/henkelmax/camera/blob/194c82e53e15f945091adccac9119e3eeb5577d8/src/main/java/de/maxhenkel/camera/ImageTools.java#L209

The flag would be added on the line above, and the entire method's parameter would now receive an array to process.
https://github.com/henkelmax/camera/blob/194c82e53e15f945091adccac9119e3eeb5577d8/src/main/java/de/maxhenkel/camera/gui/CameraScreen.java#L78

I would do it on my own, but I don't know how to configure the environment, if you could tell me how I can deploy it or know any guide, I would love to be able to contribute, thanks.

Minecraft version: 1.18.2

**Comment by henkelmax** [comment]
Uploading more than one image would cause the Minecraft network thread to hang until everything is uploaded. This would cause the server to completely freeze. All the limitations of image sizes and upload limits is carefully chosen to avoid these issues.
