### ISSUE TITLE
Game crashes when I take a picture

### ISSUE THREAD

**Issue by lolololeerre** [henkelmax/camera#62]
Hello! I've been trying to use the camera on my single player **and** multiplayer game and my game just stops working and takes me to the starting screen. I don't know why this happens because I use it on the 1.19 forge version (forge 41.1.0) and the version of the mod is 1.0.6 which is supposed to be the one for 1.19.  I've tried using other mods and they work perfectly fine (endermail, croptopia, securitycraft, minecraft comes alive reborn, revive players, tombstone, journeymap). If you could please fix this or tell me why this happens that would be great! I saw two more people that asked about the same problem but they didn't recieve an answer, so please answer this one so that people with the same problem can also fix their issue. If the image doesn't load, this is what the game says aftter is crashes: Internal Exception: java.lang.illegalstatexception: rendersystem called from wrong thread. I think i've provided all the info for you guys to solve this or give me an answer, so please do not close this issue report saying I didn't fill the requirements. Thank you!

It's like this:
-I open the camera
-I take the picture
-the game goes black and then tells me the issue

(I don't know how to put logs here)

UPDATE: when I open my game again the picture is there and it looks fine. the picture thing just works sometimes, I've tried it like 5 times and just 1 of them worked and the image showed. It still bothers me that the game crashes and I have to reopen it to look at the picture.

![image](https://user-images.githubusercontent.com/117854996/200909664-69707646-22d1-4023-805a-c1b87139776a.png)

**Comment by henkelmax** [comment]
Please fill out the bug template and provide logs.

**Comment by henkelmax** [comment]
Closed due to inactivity.
