### ISSUE TITLE
Copying albums

### ISSUE THREAD

**Issue by Dr01000111** [henkelmax/camera#63]
**Is your feature request related to a problem? Please describe.**
The Ability to copy albums by filling the album with the same amount of paper that is in the album you want to copy.

**Describe the solution you'd like**
say if you have a album with 32 pictures in it and you wanted to copy it. you put 32 paper in a new album and combine them in the crafting table and now you have 2 of the same album.

**Describe alternatives you've considered**
A anvil or smiting table could also be used to copy or a special item like a book print could be crafted with a album to get a copy

**Additional context**
This would be good for a big server for instance like a news paper that you have to copy a lot of pictures for

**Comment by henkelmax** [comment]
Putting paper in an album to copy it is a very convoluted process and not really clear on how to use it. Sorry, but I will only implement features that are easy and clear to the user. Also not really sure on how to show such a recipe in JEI.
