### ISSUE TITLE
game crashes on 1.18.2 but only on windows 11

### ISSUE THREAD

**Issue by C0smoPlays** [henkelmax/camera#64]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
the game crashes after a few secinds after loading into a world, but only on windows 11. I say this becaause I'm hosting a server with this mod enabled, and one of our players has windows 11, me and other players on windows 11 are fine, but this one crashes

**Steps to reproduce the issue**
1. own windows 11
2. launch minecraft 1.18.2 in forge version 40.1.85
3. start a world

**Expected behavior**
not crashing

**Log files**
no log given, only exit code -1

**Versions**
- Minecraft version 1.18.2
- Forge version 40.1.85
- Mod version 1.0.5

**Other mods**
(note, all other mods in this list have worked together it's just when the camera mod is enabled that it causes a crash)
alex's mobs
antique atlas
architectury API
AutoRegLib
BIomes O' Plenty
Optifine
Bookshelf (code library)
Bucolic Origins
Caelus API
Camera mod
citadel
cloth config api
coins je
create
creativecore
curios API
Drip SPunds
Feature NBT Deadlock Be Gone
Flywheel
GeckoLib
Integrated Dungeons and Structures
Just Enough Items (JEI)
Mahou Tsukai
Mana and Artifice
Mantle
Moonlight Lib
**Screenshots (Optional)**
Screenshots of the issue.
Origins (Forge)
Origins: Classes (Forge)
Pehkui
Quark
Quark Oddities
Simple Shops
Simple Voice Chat
Sound Physics Remastered
Supplementaries
TerraBlender (Forge)
Tinkers Construct
Warden & Sculk
You Died

**Comment by henkelmax** [comment]
I can't do anything without logs.
Please also test if this happens with just the mod installed.

**Comment by henkelmax** [comment]
Closed due to inactivity
