### ISSUE TITLE
Camera Mod Implementation Mixin Issue

### ISSUE THREAD

**Issue by VeguiDev** [henkelmax/camera#67]
**Bug description**
When run the debug client on development the minecraft startup fails.

**Steps to reproduce the issue**
1. Clone this repo '[farfania-camera-app](https://github.com/farfania/farfania-camera-app.git)'
2. And execute this command './gradlew runClient'
3. See error

**Expected behavior**

**Log files**
The log file [https://pastebin.com/U47U5nQ7](https://pastebin.com/U47U5nQ7).

**Versions**
- Minecraft version 1.16.5
- Forge version 36.2.39
- Mod version 1.0.14

**Other mods**
In this development enviroment are installed as dependency the mod `EyeMod` and the `Camera Mod`.

**Comment by henkelmax** [comment]
Sorry I will only accept issues with the actual mod. Not the development environment of a fork.
