### ISSUE TITLE
Disconected from server when picture taken.

### ISSUE THREAD

**Issue by hanszzz123** [henkelmax/camera#71]
**Please read the [FAQ](https://modrepo.de/minecraft/camera/faq) before submitting a bug report!**

**Bug description**
Disconected from server when picture taken, java.lang.IllegalStateException: Rendersystem called from wrong thread

**Steps to reproduce the issue**
1. Go to take a picture
2. Click on 'right click'
3. See error

**Expected behavior**
picture taken normally

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version:1.19
- Forge version:1.19
- Mod version: Most recent 1.19

**Other mods**
No other mods, just a server.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please provide logs like stated in the template.
Does this also happen in 1.19.2 or 1.19.4?
Because the version you are using is not supported anymore.

**Comment by hanszzz123** [comment]
java.lang.illegalstateexception rendersistem called from wrong tread
Unsure for newer versions, I have a mod pack for 1.19

**Comment by henkelmax** [comment]
1.19 itself is not supported anymore. If this still happens in 1.19.2 or .4 I can look into it. But for that I need the full logs.

**Comment by henkelmax** [comment]
Closed due to inactivity
