### ISSUE TITLE
Transparency for uploaded PNGs within a picture frame

### ISSUE THREAD

**Issue by DeviousJordz** [henkelmax/camera#75]
**Is your feature request related to a problem? Please describe.**
Me and my friends like adding images to help with role-playing. Adding transparency for images in picture frames would unlock a lot of possibilities.

**Describe the solution you'd like**
Is it at all possible to allow for transparency on an uploaded image in game? I think it's a great opportunity to expand the mod.

**Describe alternatives you've considered**
I'm unsure if there are other mods with a similar feature, but the camera mod works incredibly well and it would be cool to allow for transparency.

**Additional context**
Example of RP purposes: My friend wants to add a picture of a microphone to make it look like an entity in the world. With a PNGs capability with transparency, it would allow him to make it look somewhat seamless. At the moment, I think it just turns the transparent parts into a solid color (black I think?).

I'm unsure how this would be implemented, but adding transparency would really enhance this mod further in my opinion. No worries if this can't be implemented, the mod is great regardless!

**Comment by henkelmax** [comment]
The frames always have a square outline. It would look very broken if uploaded images would have transparency.

**Comment by henkelmax** [comment]
Also duplicate of #25
