### ISSUE TITLE
Images Placed West or East Appear Dark

### ISSUE THREAD

**Issue by Jowonny** [henkelmax/camera#77]
**Bug description**
When a Picture is placed in a frame facing to the West it is completely blacked out (Still there just very dark)
A similar effect happens to the East although it is much less extreme (Just darker)

**Steps to reproduce the issue**
1. Place a Frame facing West (or East)
2. Insert an Image
3. Image will appear black (or darker than usual) 

**Expected behavior**
The image would look the same as it would if it were placed facing North or South (Lighter)

**Log files**
https://gist.github.com/Jowonny/01786a40842cf740a1fb26fed63b90fa

**Versions**
- 1.20.1
- 47.0.35
- 1.20.1-1.0.3

**Other mods**
This has been tested with and without other mods, both times the error occurs

**Screenshots (Optional)**
![North and West](https://github.com/henkelmax/camera/assets/103321390/1fe8c946-f9f5-4cfa-9c1a-8874c117b7cc)
![East and South](https://github.com/henkelmax/camera/assets/103321390/31bc4277-31f9-4599-8c46-891efa4b26d2)

**Comment by henkelmax** [comment]
Doesn't happen for me:
![image](https://github.com/henkelmax/camera/assets/13237524/704ace36-1566-4588-aeb3-701ef741db6a)

**Comment by henkelmax** [comment]
Nevermind i can confirm it, somehow only happens when in positive Y coordinates.
