### ISSUE TITLE
1.19.0 - Disconnecting Players from Server When Taking Photo

### ISSUE THREAD

**Issue by curvytervy** [henkelmax/camera#78]
**Bug description**
Server is a multiplayer server hosted by pebble host and is run with forge 1.19.0.  When players try to take in-game photos it disconnects them from the world and the following error appears: "Internal Exception: java.lang.IllegalStateException: Rendersystem called from wrong thread". Upon rejoining the game, a piece of paper is taken from the inventory, but there is no picture. Uploading pictures by 'shift' + 'right-click' does work and properly uploads all pictures and places them within inventories.

**Steps to reproduce the issue**
1. Go to 'Camera'
2. Click on 'Right-Click x2'

**Expected behavior**
Photo of in-game gameplay is produced and placed in the player's inventory.

**Log files**
Log doesn't show much but what occured was I joined the game, took out my camera, and tried to take the picture:

https://mcpaste.io/f66f1b0579c03eed 

**Versions**
- Minecraft version: 1.19
- Forge version: 1.19
- Mod version: 1.19-1.0.6

**Other mods**
alexsmobs-1.19.4.jar
architectury-5.14.84-forge.jar
balm-forge-1.19.2-4.5.7.jar
cfm-7.0.0-pre34-1.19.jar
citadel-2.1.4-1.19.jar
cloth-config-8.2.88-forge.jar
corpse-1.19-1.0.8.jar
CreativeCore_FORGE_v2.8.5_mc1.19.2.jar
Croptopia-1.19-FORGE-2.0.8.jar
DungeonsArise-1.19-2.1.51-beta.jar
elevatorid-1.19-1.8.6.jar
FarmersDelight-1.19-1.2.0.jar
geckolib-forge-1.19-3.1.28.jar
Jade-1.19-forge-7.7.1.jar
journeymap-1.19-5.8.5-forge.jar
MoreVanillaArmor-1.19-4.0.4.jar
naturalist-forge-2.1.1-1.19.2.jar
Oh_The_Biomes_You'll_Go-forge-1.19-2.0.0.7.jar
PlayerRevive_FORGE_v2.0.6_mc1.19.jar
RoughlyEnoughItems-9.1.595.jar
sophisticatedbackpacks-1.19-3.18.9.661.jar
sophisticatedcore-1.19-0.4.10.87 .jar
TerraBlender-forge-1.19-2.0.0.120 .jar
trashslot-forge-1.19-12.0.2.jar
waystones-forge-1.19.2-11.4.0.jar

**Screenshots (Optional)**
<img width="1280" alt="Screenshot 2023-07-06 233355" src="https://github.com/henkelmax/camera/assets/138844775/a0205d37-f107-4a00-9270-0a34ea8262ed">

**Comment by henkelmax** [comment]
This version is no longer supported, sorry.

**Comment by curvytervy** [comment]
okay! thank you :)
