### ISSUE TITLE
REI incompatibility crash

### ISSUE THREAD

**Issue by Zernaie** [henkelmax/camera#79]
**Bug description**
Seemingly incompatibility with REI causing a crash upon uploading a photo
Unsure if it is confirmed that REI will not recieve support but I will post anyway

**Steps to reproduce the issue**
Use REI
Load into any game
Upload photo

Some times it works, it seems to be more dependent on which file you upload
not sure what causes it other than something REI related
Most of the time it just crashes, just the player who uploaded no one else

**Expected behavior**
Photo uploads into a image item without crashing the client

**Log files**
[crash-2023-07-27_18.29.36-client.txt](https://github.com/henkelmax/camera/files/12188948/crash-2023-07-27_18.29.36-client.txt)
[crash-2023-07-27_18.56.26-client.txt](https://github.com/henkelmax/camera/files/12188949/crash-2023-07-27_18.56.26-client.txt)
[crash-2023-07-27_18.59.07-client.txt](https://github.com/henkelmax/camera/files/12188950/crash-2023-07-27_18.59.07-client.txt)
[crash-2023-07-27_19.03.42-client.txt](https://github.com/henkelmax/camera/files/12188955/crash-2023-07-27_19.03.42-client.txt)
the picture causing crash in example
[https://github.com/henkelmax/camera/assets/52133154/22eda638-46bd-4bc9-8d56-2270d0ebed81](url)

**Versions**
Latest forge (40.2.10 at time)
1.18.2-1.0.6

**Other mods**
Architectury
Cloth config
(REI dependencies, though it only crashes with REI)

**Screenshots (Optional)**
https://github.com/henkelmax/camera/assets/52133154/ac50c160-6c65-4016-bf0a-c8f8b009e302

**Comment by henkelmax** [comment]
1.18.2 is no longer supported, sorry. If this still happens in newer versions, please let me know.
