### ISSUE TITLE
Can't place Image frame on floor

### ISSUE THREAD

**Issue by Izunyaaan** [henkelmax/camera#80]
**Bug description**
Right clicking image frame on floor wont place it

**Steps to reproduce the issue**
1. Obtain image frame
2. Hold it
3. Right click while looking at a floor
4. Isn't placed

**Expected behavior**
Like item frames can be placed on floor

**Versions**
- Minecraft version 1.18.2
- Forge version 40.2.9
- Mod version 1.18.2-1.0.6

**Comment by henkelmax** [comment]
Images are only able to be placed on walls.

**Comment by Izunyaaan** [comment]
Ah thank you. Sorry for wasting your time
