### ISSUE TITLE
Crashes when uploading image

### ISSUE THREAD

**Issue by YuGodo** [henkelmax/camera#82]
**Bug description**
My game crashes when i try to upload a picture

**Steps to reproduce the issue**
I get a camera control right click and then press on upload 2s later game crash

**Expected behavior**
I get a camera control right click and then press on upload and then i can get an image

**Log files**

[<script src="https://gist.github.com/YuGodo/c930de6b5a67348b68725a0867524335.js"></script>/).

**Versions**
- Minecraft version:1.18.2
- Forge version:40.2.9
- Mod version:1.0.6

**Other mods**
Vaulthunters 3rd edition modpack version 3.11.5

**Comment by henkelmax** [comment]
This version is no longer supported, sorry.

**Comment by YuGodo** [comment]
so i gotta downgrade?

**Comment by henkelmax** [comment]
Downgrade?

**Comment by YuGodo** [comment]
to a older version

**Comment by YuGodo** [comment]
fixed the problem was smt to do with my file explorer
