### ISSUE TITLE
[1.18.2] Image uploading fails entirely in my case

### ISSUE THREAD

**Issue by Gronglegrowth** [henkelmax/camera#84]
**Bug description**
Attempting to upload an image with the button in the camera gui results in nothing happening, for me. I run the game via the flatpak of Prism Launcher, on Linux, and I suspect thats the issue. As I have no other launchers nor do I feel like installing another in a different way to test, I'm not sure entirely.

**Steps to reproduce the issue**
1. Be running the game on Linux using a launcher installed via flatpak
2. Open the camera gui
3. Click upload image button

**Expected behavior**
On clicking the upload button, it should allow me to select an image

**Log files**
https://paste.gg/p/anonymous/606890c3f64648f0ad388177f30b622b

**Versions**
- Minecraft version - 1.18.2
- Mod loader - Forge
- Mod loader version - 40.2.0
- Mod version - 1.0.6

**Comment by henkelmax** [comment]
Don't use flatpack. It creates a sandbox and most likely doesn't allow you to open files.
