### ISSUE TITLE
Hovering force-shows the image

### ISSUE THREAD

**Issue by QwertRvg** [henkelmax/camera#87]
**Bug description**
The first time hovering over an Image item in the inventory force-shows it full-screen.
When re-entering a world / restarting the game, this again happens on the first hover.

**Steps to reproduce the issue**
1. Take a picture using the camera item.
2. Open the inventory.
3. Hover over the Image item.

**Expected behavior**
That it would not force-show the image and instead just the tooltip.
The behavior it has when hovering over it a second time.

**Log files**
https://gist.github.com/QwertRvg/3bb1732e15fa92bba4b31c1c0efc7527

**Versions**
- 1.20.1
- Forge
- 47.2.0
- 1.0.6

**Other mods**
After removing mods from the pack I was playing I found out that the issue only persisted if Legendary Tooltips was also installed.

**Comment by henkelmax** [comment]
I am not able to reproduce this issue at all.

**Comment by QwertRvg** [comment]
Okay so I just checked and the issue specifically persists when the config option "Render Item Model" of the Legendary Tooltips mod is set to "All."

With that config option, the tooltip renders the item as a 3d model, for every item. This does also cause this issue though.
