### ISSUE TITLE
1.18.2 Keep taking black pictures

### ISSUE THREAD

**Issue by donmor** [henkelmax/camera#90]
### Bug description

Any taken photo is rendered completely black. There are lots of `Enum 0x8501 is currently not supported` in log (attached below)

### Minecraft version

1.18.2

### Mod version

1.18.2-1.0.6

### Mod loader and version

Forge 40.2.17

### Steps to reproduce

- Start game with this mod
- take a photo and the resulting photo is completely black

### Log files

https://gist.github.com/donmor/ee1ab1096390a4744c6cbc99d0877603

**Comment by henkelmax** [comment]
This Minecraft version is no longer supported, sorry. If this still happens in 1.19.2, 1.20.1 or 1.20.4, please let me know.
