### ISSUE TITLE
images blurry when taken, also JEI shows up.

### ISSUE THREAD

**Issue by moonpls** [henkelmax/camera#92]
### Bug description

I'm doing modded minecraft with around 200 mods, and rubidium with shaders. Every time i take a picture with the camera, it is blurry, and is also blurry when put in an item frame, also JEI shows up on the side.

### Minecraft version

1.18.2

### Mod version

1.18.2-1.0.6

### Mod loader and version

Forge 40.2.9

### Steps to reproduce

1. Open the camera
2. Take a picture
3. it comes out blurry with JEI on the side.
4. Put it in an item frame.
5. It is still blurry

### Expected behavior

I expected the image to be clear and no jei to show up.

### Log files

https://gist.github.com/moonpls/49b252295e3c9f0b721a4e7f2cfa256c

### Screenshots

![Screenshot 2024-04-05 015926](https://github.com/henkelmax/camera/assets/166105562/5e28f57c-7f8b-4035-9090-21a5a1156c4d)

**Comment by moonpls** [comment]
also ive tried turning off shaders, does the same thing.

**Comment by henkelmax** [comment]
This version is no longer supported, sorry.
