### ISSUE TITLE
For some reason Camera mod items dont show up

### ISSUE THREAD

**Issue by Gintas2002** [henkelmax/camera#93]
### Bug description

I am using many mods 173 mods, and the Camera mod is the only mod that doesn't show in the Creative menu or JEI for some reason??

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.8

### Mod loader and version

47.2.0

### Steps to reproduce

Go into creative and it doesn't show up when searched for camera mod items

### Log files

https://gist.github.com/Gintas2002/330d47bedd8ca4965bf8f3de4bd1dcee

**Comment by henkelmax** [comment]
Are you able to craft them?

**Comment by Nix2929** [comment]
I also have the same error, I have the mod installed and there is no trace of the mod when I open a world

**Comment by Nix2929** [comment]
![image](https://github.com/henkelmax/camera/assets/166357389/75613c65-2d91-47eb-b8fa-079da12b0202)
the only way to get the camera is with commands

**Comment by henkelmax** [comment]
> the only way to get the camera is with commands

Did you try crafting the item?

**Comment by henkelmax** [comment]
Closed due to inactivity.
