### ISSUE TITLE
Cause's invalid player data

### ISSUE THREAD

**Issue by foodforthepoor** [henkelmax/camera#96]
### Bug description

When i place a picture in a frame and i leave i can no longer join the world it says invalid player data

### Minecraft version

1.21

### Mod version

1.21-1.0.11

### Mod loader and version

Neoforge - 21.0.94

### Steps to reproduce

1,take a photo 2.put in a image frame 3.leave world 4.Invalid player data by the way to make it not say invalid player data just disable/ delete the mod

### Log files

i fixed the issue

### Screenshots

i did not take a screen shot sorry

**Comment by henkelmax** [comment]
Fixed with a5fb22c42e15ec1cc60929191046b6f19e25e4ff
