### ISSUE TITLE
crashes the game instantly

### ISSUE THREAD

**Issue by foodforthepoor** [henkelmax/camera#97]
### Bug description

When i right click to look at a picture it crashes my game and if i try and resize a image frame it also crashes instantly

### Minecraft version

1.21

### Mod version

1.21-1.0.12

### Mod loader and version

Neoforge - 21.0.133

### Steps to reproduce

1. take a photo 2. open the photo crashes 1. place a image frame 2. shift right click it crashes

### Log files

i dont have an logs

### Screenshots

i also don't have a screen shot

**Comment by henkelmax** [comment]
I am not able to reproduce your issue. You also didn't provide any logs so I can't investigate the issue anyways.
